### ISSUE TITLE
zarrdump fails with IndexError

### ISSUE THREAD

**Issue by oliverwm1** [oliverwm1/zarrdump#4]
```
(fv3net) OliWM@oliwm-vm:~/repos/nudge-to-obs-manuscript-workflow/fv3net$ zarrdump gs://vcm-ml-intermediate/2020-01-06-C384-grid-spec-with-area-dx-dy.zarr
Traceback (most recent call last):
  File "/home/OliWM/miniconda3/envs/fv3net/bin/zarrdump", line 8, in <module>
    sys.exit(dump())
  File "/home/OliWM/miniconda3/envs/fv3net/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/OliWM/miniconda3/envs/fv3net/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/OliWM/miniconda3/envs/fv3net/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/OliWM/miniconda3/envs/fv3net/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/OliWM/miniconda3/envs/fv3net/lib/python3.7/site-packages/zarrdump/core.py", line 20, in dump
    if _zarr_object_is_xarray_dataset(zarr_obj):
  File "/home/OliWM/miniconda3/envs/fv3net/lib/python3.7/site-packages/zarrdump/core.py", line 56, in _zarr_object_is_xarray_dataset
    array = obj[array_keys[0]]
IndexError: list index out of range
```

**Comment by oliverwm1** [comment]
This happened because the consolidated metadata was out of date.
